openapi: 3.0.0
info:
  title: Sample Pet Store API
  description: A sample API for testing the OpenAPI to HTTP extension
  version: 1.0.0
servers:
  - url: https://api.petstore.example.com/v1
    description: Production server
  - url: http://localhost:3000/v1
    description: Development server

paths:
  /pets:
    get:
      summary: List all pets
      description: Returns a list of all pets in the store
      operationId: listPets
      parameters:
        - name: limit
          in: query
          description: Maximum number of pets to return
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 100
            default: 20
        - name: tag
          in: query
          description: Filter pets by tag
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
    
    post:
      summary: Create a pet
      description: Creates a new pet in the store
      operationId: createPet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPet'
      responses:
        '201':
          description: Pet created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'

  /pets/{petId}:
    get:
      summary: Get a pet by ID
      description: Returns a single pet
      operationId: getPetById
      parameters:
        - name: petId
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Pet details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Pet not found
    
    put:
      summary: Update a pet
      description: Updates an existing pet
      operationId: updatePet
      parameters:
        - name: petId
          in: path
          description: ID of pet to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPet'
      responses:
        '200':
          description: Pet updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
    
    delete:
      summary: Delete a pet
      description: Deletes a pet from the store
      operationId: deletePet
      parameters:
        - name: petId
          in: path
          description: ID of pet to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Pet deleted successfully

  /users:
    post:
      summary: Create a user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
              properties:
                username:
                  type: string
                  minLength: 3
                  maxLength: 20
                  pattern: '^[a-zA-Z0-9_]+$'
                email:
                  type: string
                  format: email
                age:
                  type: integer
                  minimum: 18
                  maximum: 120
                isActive:
                  type: boolean
                  default: true
                roles:
                  type: array
                  items:
                    type: string
                    enum: [admin, user, guest]
                  minItems: 1
      responses:
        '201':
          description: User created

components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Fluffy
        tag:
          type: string
          example: cat
        status:
          type: string
          enum: [available, pending, sold]
          example: available
        price:
          type: number
          format: double
          minimum: 0
          example: 99.99
        birthDate:
          type: string
          format: date
          example: '2020-01-15'
    
    NewPet:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 50
        tag:
          type: string
        status:
          type: string
          enum: [available, pending, sold]
          default: available
        price:
          type: number
          format: double
          minimum: 0
